# Generated by Django 4.0.5 on 2022-06-14 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('licencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=50)),
                ('tipo_licencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('matricula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('propietario', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('fk_vehiculo_conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conductor')),
            ],
        ),
    ]
